# Generated by Django 6.0 on 2025-12-16 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_zh', models.CharField(default='第一课', max_length=100, verbose_name='标题 (中文)')),
                ('title_ru', models.CharField(default='Урок 1', max_length=100, verbose_name='标题 (俄语)')),
                ('exercise_data', models.TextField(blank=True, help_text='请直接将原来 .json 文件中的全部内容复制粘贴到这里', verbose_name='习题数据 (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程列表',
            },
        ),
        migrations.CreateModel(
            name='TextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_zh', models.CharField(max_length=255, verbose_name='课文 (汉字)')),
                ('text_pinyin', models.CharField(max_length=255, verbose_name='拼音')),
                ('text_ru', models.CharField(max_length=255, verbose_name='翻译 (俄语)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='顺序 (数字越小越靠前)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='learning.lesson')),
            ],
            options={
                'verbose_name': '课文句子',
                'verbose_name_plural': '课文句子',
                'ordering': ['order'],
            },
        ),
    ]
